### ISSUE TITLE
Chat Widget Issue: Failed to fetch connectionDetails with createParticipantConnection

### ISSUE THREAD

**Issue by gtonye** [amazon-connect/amazon-connect-chat-ui-examples#86]
Hi,

We're working on integrating the Amazon Connect widget to help our customers engage with the Live Agents. We want to use the custom widgets but are facing some challenges (more details after) when setting up the chat widget on a website.

When the SDK attempts to `createParticipantConnection`, it returns a 403 without any logs (server side) and with these in the _browser dev tools_:
* Failed to fetch connectionDetails with createParticipantConnection
* User is not authorized to access this resource with an explicit deny

We would love some guidance on how to resolve it or a way to investigate the root cause.

> Let me know if this isn't the right place for this question.

Thank you,

#### Our setup

We follow the guidelines from [this documentation](https://github.com/amazon-connect/amazon-connect-chat-ui-examples/blob/master/cloudformationTemplates/asyncCustomerChatUX/README.md):
* We have created an Amazon Connect Instance
* We have imported and published the 'Basic Chat Flow'
* We have taken note of the `contactFlowId` and `instanceId`
* We have updated the admin role and the routine profile as indicated [here](https://github.com/amazon-connect/amazon-connect-chat-ui-examples/blob/master/README.md#enabling-chat-in-an-existing-amazon-connect-contact-center)
* We have deployed the cloud formation template (and set the `contactFlowId` and `instanceId` parameters accordingly)
* Setup the widget with the `contactFlowId`, `instanceId` and the API Gateway endpoint from cloud formation deployment.

#### Issue we are facing

When using the [custom widget](https://github.com/amazon-connect/amazon-connect-chat-ui-examples/blob/master/cloudformationTemplates/startChatContactAPI/customBuildIndex.html), it will error when making the call to `https://participant.connect.us-west-2.amazonaws.com/participant/connection `

The call returns with a 403 and the following message:
```json
{
    "message": "User is not authorized to access this resource with an explicit deny"
}
```

The more detailed stack trace from the dev tool console is:
```json
{
  "_debug": {
    "reason": "Failed to fetch connectionDetails with createParticipantConnection",
    "_debug": {
      "type": "UnknownError",
      "message": "User is not authorized to access this resource with an explicit deny",
      "stack": ["UnknownError: User is not authorized to access this resource with an explicit deny", "    at Object.extractError (https://hidden-domain.ngrok.io/amazon-connect-chat-interface.js:2:895908)", "    at constructor.extractError (https://hidden-domain.ngrok.io/amazon-connect-chat-interface.js:2:901104)", "    at constructor.callListeners (https://hidden-domain.ngrok.io/amazon-connect-chat-interface.js:2:918830)", "    at constructor.emit (https://hidden-domain.ngrok.io/amazon-connect-chat-interface.js:2:918541)", "    at constructor.emitEvent (https://hidden-domain.ngrok.io/amazon-connect-chat-interface.js:2:912221)", "    at constructor.e (https://hidden-domain.ngrok.io/amazon-connect-chat-interface.js:2:907727)", "    at r.runTo (https://hidden-domain.ngrok.io/amazon-connect-chat-interface.js:2:945427)", "    at https://hidden-domain.ngrok.io/amazon-connect-chat-interface.js:2:945633", "    at constructor.<anonymous> (https://hidden-domain.ngrok.io/amazon-connect-chat-interface.js:2:908016)", "    at constructor.<anonymous> (https://hidden-domain.ngrok.io/amazon-connect-chat-interface.js:2:912277)"],
      "statusCode": 403
    }
  },
  "connectSuccess": false,
  "connectCalled": true,
  "metadata": null
}
```

#### Notes

I am adding below additional information that might be helpful:
* For the cloudFormation template and the 'Basic Chat Flow', we have used the code from the `master` branch.
* The call to `https://hidden.execute-api.us-east-1.amazonaws.com/Prod` is successful and returns:
```json
{
  "data": {
      "startChatResult": {
          "ContactId": "bdxxe33y-4a8a-xx78-ayy6-099ae59f20c7",
          "ParticipantId": "3dyy9162-41c8-4yy1-93b2-d554xxd075xx",
          "ParticipantToken": "hidden"
      }
  }
}
```
* Everything is deployed in the `us-east-1` region

**Comment by gtonye** [comment]
We managed to resolve the issue: The issue was caused by the StartChat and CreateParticipant calling two different regions


There's a difference between the [customizable widget](https://github.com/amazon-connect/amazon-connect-chat-ui-examples/blob/master/cloudformationTemplates/startChatContactAPI/customBuildIndex.html) and the [widget](https://github.com/amazon-connect/amazon-connect-chat-ui-examples/blob/master/cloudformationTemplates/startChatContactAPI/widgetIndex.html) on [this line](https://github.com/amazon-connect/amazon-connect-chat-ui-examples/blob/96985f4e6f3f670fe33baaf0affca92a4d2280e6/cloudformationTemplates/startChatContactAPI/widgetIndex.html#L83)

In the customizable widget, it would be safer to change [this](https://github.com/amazon-connect/amazon-connect-chat-ui-examples/blob/96985f4e6f3f670fe33baaf0affca92a4d2280e6/cloudformationTemplates/startChatContactAPI/customBuildIndex.html#L114) to:

```js
  session = connect.ChatSession.create({
      chatDetails: result.data.startChatResult,
      options: {
        region: awsDeploymentRegion, // region of the Amazon Connect instance
      },
      type: "CUSTOMER"
  });
```
